# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OM_jxArjNuDGdJ31-DAU3cq946OgQ9Qq
"""

from google.colab import files
uploaded = files.upload()

# 1. Kutubxonani chaqiramiz
import pandas as pd

# 2. Datasetni yuklaymiz (Colabga fayl yuklangan bo'lishi kerak)
df = pd.read_csv('22 (1).csv')

# 1️⃣ Ustun va satrlar sonini chiqarish
rows, cols = df.shape
print("Satrlar soni:", rows)
print("Ustunlar soni:", cols)

# 2️⃣ NaN qiymatli satrlarni o'chirish
df_clean = df.dropna()

# 3️⃣ Nechta satr o'chganini chiqarish
deleted_rows = rows - df_clean.shape[0]
print("O'chirilgan satrlar soni:", deleted_rows)

# 4️⃣ NaNsiz datasetni chiqarish
print("\nNaN qiymatsiz dataset:")
print(df_clean)

# 5️⃣ Eng muhim ustun bo'yicha groupBy qilish
# Bu datasetda muhim ustun sifatida 'species' ni ishlatyapmiz
grouped = df_clean.groupby("species").size()

print("\nSpecies bo'yicha guruhlash natijasi:")
print(grouped)